### PR TITLE
First attempt to add DatabaseErrorHandler

### PR DESCRIPTION
**Pull request by brody2consult**
In response to: https://mail.google.com/mail/ca/u/0/#inbox/13bd59554d89aa4f here is the ability to use a SQLiteOpenHelper with a DatabaseErrorHandler.

### CODE REVIEW

**Comment by rage28** [comment]
Hi,

Any idea when this feature will have a release?

**Comment by brodybits** [comment]
The problem is that we need a test case for this enhancement. I think we
would have to test this with a corrupt database file. Don't know when I
will get a chance to look at it.

Chris
@brodybits

**Comment by rage28** [comment]
Is it enough if you have any corrupt database? Or any specific type of corruption (as listed on their [site](https://www.sqlite.org/howtocorrupt.html))?

**Comment by brodybits** [comment]
I just made a simple corrupt database test in this branch: https://github.com/brodybits/sqlcipher-android-tests/tree/first-corrupt-database-test

Following the hint at http://stackoverflow.com/questions/26966905/can-i-deliberately-corrupt-an-sqlite3-database-for-testing I took the existing unencrypted.db from sqlcipher-android-tests and removed blocks of `00` bytes (using vim as described here: http://timmurphy.org/2013/07/27/editing-a-file-in-hex-mode-in-vim/).

Here is a hexdump of my corrupted database (note that extra `00` blocks are suppressed and shown by `*`):

```
00000000  53 51 4c 69 74 65 20 66  6f 72 6d 61 74 20 33 00  |SQLite format 3.|
00000010  10 00 01 01 00 40 20 20  00 00 00 02 00 00 00 03  |.....@  ........|
00000020  00 00 00 00 00 00 00 00  00 00 00 01 00 00 00 04  |................|
00000030  00 00 00 00 00 00 00 03  00 00 00 01 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 02  |................|
00000060  00 2d e2 22 0d 00 00 00  01 0f da 00 0f da 00 00  |.-."............|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000000a0  00 00 00 00 00 00 00 00  00 00 24 01 06 17 11 11  |..........$.....|
000000b0  01 35 74 61 62 6c 65 74  31 74 31 03 43 52 45 41  |.5tablet1t1.CREA|
000000c0  54 45 20 54 41 42 4c 45  20 74 31 28 61 2c 62 29  |TE TABLE t1(a,b)|
000000d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000110  00 00 00 00 00 00 00 00  00 00 24 01 03 2f 2d 6f  |..........$../-o|
00000120  6e 65 20 66 6f 72 20 74  68 65 20 6d 6f 6e 65 79  |ne for the money|
00000130  74 77 6f 20 66 6f 72 20  74 68 65 20 73 68 6f 77  |two for the show|
00000140  0a                                                |.|
```

For comparison, here is the hexdump of the original (unencrypted) db (again, extra `00` blocks suppressed and shown by `*`):

```
00000000  53 51 4c 69 74 65 20 66  6f 72 6d 61 74 20 33 00  |SQLite format 3.|
00000010  10 00 01 01 00 40 20 20  00 00 00 02 00 00 00 03  |.....@  ........|
00000020  00 00 00 00 00 00 00 00  00 00 00 01 00 00 00 04  |................|
00000030  00 00 00 00 00 00 00 03  00 00 00 01 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 02  |................|
00000060  00 2d e2 22 0d 00 00 00  01 0f da 00 0f da 00 00  |.-."............|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000fd0  00 00 00 00 00 00 00 00  00 00 24 01 06 17 11 11  |..........$.....|
00000fe0  01 35 74 61 62 6c 65 74  31 74 31 03 43 52 45 41  |.5tablet1t1.CREA|
00000ff0  54 45 20 54 41 42 4c 45  20 74 31 28 61 2c 62 29  |TE TABLE t1(a,b)|
00001000  01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00001010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00002000  0d 00 00 00 01 0f da 00  0f da 00 00 00 00 00 00  |................|
00002010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00002fd0  00 00 00 00 00 00 00 00  00 00 24 01 03 2f 2d 6f  |..........$../-o|
00002fe0  6e 65 20 66 6f 72 20 74  68 65 20 6d 6f 6e 65 79  |ne for the money|
00002ff0  74 77 6f 20 66 6f 72 20  74 68 65 20 73 68 6f 77  |two for the show|
```

I will finish reworking the changes based on the most recent changes (in the `master` branch) and issue a new pull request.

**Pull request closed without merging**
