### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by brodybits**
Proposed, as discussed in #298:
- remove duplicate & nonsensical SQLCIPHER_CFLAGS
- omit extension loading, memroy management, and column metadata (not used here)
- Several more defines from <https://www.sqlite.org/compile.html#recommended_compile_time_options>:
  - SQLITE_OMIT_DECLTYPE
  - SQLITE_OMIT_PROGRESS_CALLBACK
  - SQLITE_OMIT_SHARED_CACHE

_P.S. This does pass the test suite on my device._

### CODE REVIEW

**Comment by developernotes** [comment]
Hi @brodybits 

I apologize for the delay in review referenced in #298. I can quickly tell you that we do plan to maintain the extension loading mechanism in SQLCipher for Android, so we won't want to remove the call to `sqlite3_enable_load_extension` within the JNI layer. More to come with the individual `CFLAG` adjustments. Thank you for looking into this, we appreciate your patience.

**Comment by brodybits** [comment]
Understood. I just updated to keep the extension loading mechanism, keep `-DNDEBUG`, and fix a commit message.

I will understand if you just want to close this one. I will keep my own build for the Cordova plugin.

**Comment by developernotes** [comment]
Hello @brodybits 

Thank you for taking a lead on identifying some of the `CFLAG` inconsistencies in the SQLCipher for Android project. I would also like to apologize for the delay in getting back to you on this, I'm sorry. I have just pushed up a commit that addresses several of the items you have identified. 

We have removed the duplicate entries, and also removed the flags which have been removed in newer version of upstream SQLite. However, flags such as `SQLITE_OMIT_COLUMN_METADATA`, and the other `SQLITE_OMIT_*` were not added, nor was `SQLITE_ENABLE_UNLOCK_NOTIFY` removed. We are aware of many organizations utilized the compiled native libraries outside of the Java/JNI layers in which we do not want to hinder their utilization of the library; unfortunately we cannot confirm usage of those functions. Given the potential risk there would need to be a very compelling reason to omit features that have been in the library since it's inception. We feel it is important to provide a unified feature set within the library across platforms, providing consistent CFLAG's as much as possible is a step in that direction. Please take a look [at the change](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/Makefile#L8-L27) introduced and let me know if you have any concerns. Thanks!

**Comment by brodybits** [comment]
Thanks @developernotes, definitely makes sense.

**Pull request closed without merging**
