### PR TITLE
Support for SQLCipher 3.4.0

### PR DESCRIPTION
**Pull request by nthtrung09it**
@gmetal I see SQLCipher has new version 3.4.0. Do you have any plan to update version 3.3.1.2.64 to 3.4.64? Tks.

### CODE REVIEW

**Comment by gmetal** [comment]
@nthtrung09it Hello, no I have no such plans. My original pull request was rejected and I no longer use sqlcipher in any of my projects, hence I do not plan on releasing any future versions.

**Comment by nthtrung09it** [comment]
@gmetal What option do you choice for encrypting your database? Can you tell me a bit about you solution? Tks very much.

**Comment by gmetal** [comment]
@nthtrung09it The projects that I am currently working on, have no need for database encryption. I know of no other solutions for encrypting relational (SQL) databases, apart from sqlcipher. However, if you are not limited to relational databases, the Realm mobile database offers encyption, although I have not used it in the past for this purpose.

**Comment by nthtrung09it** [comment]
@gmetal Thanks for your quick response.

**Pull request closed without merging**
