### PR TITLE
Add missing method to MatrixCursor.Rowbuilder class

### PR DESCRIPTION
**Pull request by attaurrehman**
Added missing add(String, Object) method for MatrixCursor.RowBuilder class that was added in API 19 and I have faced this problem in my project.

### CODE REVIEW

**Comment by developernotes** [comment]
Hello @attaurrehman 

Thank you for your interest in helping extend SQLCipher for Android!  We prefer pull requests also include corresponding tests within the separate SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests).  Would you mind submitting a subsequent request testing this addition?

Also, please contact us directly regarding the contributor agreement so we can accept your changes, more info [here](https://www.zetetic.net/contributions/).  Thanks!

**Comment by attaurrehman** [comment]
Hi, 

I'll glad to add a test case for this fix. However, I'm wondering what kind you usually have a missing method in a given class that has been added in the later versions of Android SDK but hasn't made it to sqlcipher yet? The method in this case is:

http://developer.android.com/intl/ko/reference/android/database/MatrixCursor.RowBuilder.html#add%28java.lang.String,%20java.lang.Object%29

**Comment by developernotes** [comment]
Hello @attaurrehman 

We would like to exercise the behavior of your addition, showing that your behavior matches that of the documentation:
>Offer value for possible inclusion if this cursor defines the given column. Columns not defined by the cursor are silently ignored.

The API differs because both the Java and native API components are snapshots of an older AOSP.

**Comment by developernotes** [comment]
Hi @attaurrehman 

I am going to close this due to inactivity regarding the addition of the test suite component. Please feel free to reopen this if it is still an issue. Thanks!

**Comment by brodybits** [comment]
https://probot.github.io/apps/stale/ (Stale bot) may be your friend.

**Comment by developernotes** [comment]
Hi @brodybits 

Thanks for sharing this, I wasn't aware of that! We will look into this further.

**Pull request closed without merging**
