### PR TITLE
Fix some NullPointerException scenarios

### PR DESCRIPTION
**Pull request by brodybits**
as reproduced in sqlcipher/sqlcipher-android-tests#13

Define SQLiteDatabase.MEMORY for in-memory database.

### CODE REVIEW

**Comment by developernotes** [comment]
Hi @brodybits 

Thanks for submitting this, along with the additional tests! One issue of note, the new test [ChangePasswordTest](https://github.com/sqlcipher/sqlcipher-android-tests/pull/14/files#diff-05c16928ba605b9dc8454fe22d5dcdfdR36) causes the test suite to crash, unfortunately [this](https://github.com/sqlcipher/android-database-sqlcipher/pull/248/files#diff-185f1232d67c73361a426f2bec829b0aR122) change doesn't effect the behavior. Two possible solutions, we could either detect the null value in the Java layer and not forward the call into the native layer, or perform a null check before we attempt to [get the raw chars](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/jni/net_sqlcipher_database_SQLiteDatabase.cpp#L132) in the native layer. I think once we have this issue addressed we can merge everything in. Thoughts?

**Comment by brodybits** [comment]
Hi @developernotes,

I will update the PR sometime next week if not over the weekend. I am thinking to check for a null value in the Java code (which seems to be done for native_key).

For some reason it didn't crash when I tested it on my own device (which is on Android 4.4.2).

As a side topic, I think it would be a little better for native_rekey to be based on a char array to be more consistent with native_key. Or could this break something?

Thanks!

**Comment by developernotes** [comment]
Hi @brodybits 

>I will update the PR sometime next week if not over the weekend.

Thanks!

>As a side topic, I think it would be a little better for native_rekey to be based on a char array to be more consistent with native_key. Or could this break something?

Agreed, though for backward compatibility, we should continue to offer the `String` variant, having it call into the `char[]` version.

**Comment by brodybits** [comment]
I just pushed another change that should fix the crash scenario.

When I looked in the native code it seems that the native_key function actually converts the char array into a string before getting the UTF characters. For native_rekey I am thinking it would be most efficient not to change it assuming we don't get any bug reports.

**Comment by developernotes** [comment]
All merged up—thanks @brodybits!

**Comment by brodybits** [comment]
Awesome!

**Pull request closed without merging**
