### PR TITLE
More info in build from source

### PR DESCRIPTION
**Pull request by hannesa2**
- open with Android Studio ignores now some local files
- build from source add info about what to do. 

This is new
image

and this 
image

### CODE REVIEW

**Comment by developernotes** [comment]
Hi @hannesa2 

Thanks for submitting this pull request. We will review this and provide feedback. Thanks!

**Comment by developernotes** [comment]
Hi @hannesa2,

There appear to be many changes to whitespace, and formatting that appear unrelated to the few changes necessary to include the additional stylized output. Would you please review those changes in your pull request and remove them. We are interested in adding the stylized output however.

We ask that you submit a contributor agreement in order for us to accept this request. More information about this agreement can be found [here](https://www.zetetic.net/contributions/). Please let us know if you have any further questions. Thanks!

**Comment by hannesa2** [comment]
> There appear to be many changes to whitespace, and formatting that appear unrelated to the few changes necessary to include the additional stylized output. Would you please review those changes in your pull request and remove them. 

Indeed, this repo uses **no code format** ! (I use automatic the common  Android Studio code formatter)
Ok, I can split code format into an own PR, but to be honest, I recommend to apply a codeformat for **complete** repo

**Comment by sjlombardo** [comment]
Hello @hannesa2 thanks for submitting this update. I'm not sure if you saw @developernotes comment earlier:

> We ask that you submit a contributor agreement in order for us to accept this request. More information about this agreement can be found [here](https://www.zetetic.net/contributions/). Please let us know if you have any further questions. Thanks!

We need to have the contributor agreement in place before moving forward with this pull request. Please review the above agreements and then contact us at support@zetetic.net with your information so we can proceed.

**Comment by developernotes** [comment]
Hi @hannesa2 

We do include an [editorconfig](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/.editorconfig) file. Do you know if your IDE is picking up on that?

**Comment by hannesa2** [comment]
@sjlombardo 
Concerning contributor agreement:  
I wrote at 15.06.19, 08:49 to support@zetetic.net to start this 

> if you wish to sign a contributor license agreement. We will then initiate the document signing process via DocuSign

So I wait for the initiate. But I'm not sure, if the pdf I sent is fine.

**Comment by hannesa2** [comment]
> We do include an [editorconfig](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/.editorconfig) file. Do you know if your IDE is picking up on that?

https://stackoverflow.com/a/46869657/1079990 it is auto-checked in Android Studio. But when I pick a random *.java file and format it, a lot changes are applied. Btw, I've a macro in my Android Studio, where I perform a format automatically.

Btw, my known best practice to keep all developer on same code style is to add following lines to `.gitignore` 

```
.idea/*
!.idea/codeStyles/
```

**Comment by sjlombardo** [comment]
Hello @hannesa2 I'm sorry but we did not receive the email about the contributor agreement. Can you please resend your information?

**Comment by hannesa2** [comment]
> I'm sorry but we did not receive the email about the contributor agreement. Can you please resend your information?

I resent it and now I got a automatic response. It seems to work now !

**Comment by developernotes** [comment]
Hi @hannesa2 

Thanks for this, we've just merged this into the master branch!

**Pull request merged**
